apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: bbpod
  name: bbpod
spec:
  containers:
  - image: yauritux/busybox-curl
    name: bbpod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
