apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: nginxc
  name: nginxc
spec:
  replicas: 1
  selector:
    matchLabels:
      run: nginxc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: nginxc
    spec:
      containers:
      - image: pamvdam/nginxc:v1.1
        name: nginxc
        ports:
        - containerPort: 8080
        resources: {}
status: {}
