apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: path-rule-ingress
  annotations:
    traefik.frontend.rule.type: PathPrefixStrip
    kubernetes.io/ingress.class: traefik
    cert-manager.io/issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    traefik.ingress.kubernetes.io/redirect-permanent: "true"
    ingress.kubernetes.io/ssl-redirect: "true"
    ingress.kubernetes.io/ssl-temporary-redirect: "false"
spec:
  backend:
    serviceName: nginxc-black
    servicePort: 80
  rules:
  - http:
      paths:
      - backend:
          serviceName: nginxc-blue
          servicePort: 80
        path: /blue
  - http:
      paths:
      - backend:
          serviceName: nginxc-red
          servicePort: 80
        path: /red
  - http:
      paths:
      - backend:
          serviceName: nginxc-yellow
          servicePort: 80
        path: /yellow
  - http:
      paths:
      - backend:
          serviceName: nginxc-purple
          servicePort: 80
        path: /purple
  - host: blue.itgildelab.net
    http:
      paths:
      - backend:
          serviceName: nginxc-blue
          servicePort: 80

  tls:
  - hosts:
    - st00node01.itgildelab.net
    secretName: st00node01-tls
