apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: pyko2
  name: pyko2
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: pyko2
  type: NodePort
status:
  loadBalancer: {}
