apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: nginx-nfs
  name: nginx-nfs
spec:
  replicas: 2
  selector:
    matchLabels:
      run: nginx-nfs
  strategy: {}
  template:
    metadata:
      labels:
        run: nginx-nfs
    spec:
      containers:
      - image: nginx:1.7.1
        name: nginx-nfs
        imagePullPolicy: Always
        volumeMounts:
          # name must match the volume name below
          - name: nfs
            mountPath: "/usr/local/nginx/html"
      volumes:
      - name: nfs
        persistentVolumeClaim:
          claimName: nfs
