apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv02
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: st99node01
    path: "/mnt/export/student01"
