apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pyco2
  name: pyco2
spec:
  containers:
  - image: pamvdam/pyco2:v4x86
    name: pyco2
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
