apiVersion: v1
kind: Pod
metadata:
  run: bb
spec:
  containers:
    image: pamvdam/astro:sf1
    name: astro
    startupProbe:
      httpGet:
        path: /health
        port: 8080
      failureThreshold: 30
      periodSeconds: 10
