apiVersion: v1
kind: Pod
metadata:
  name: init-git
  labels:
    app: init
spec:
  containers:
  - name: app-container
    image: alpine
    command: ['sh', '-c', 'echo The app is running!','sleep 30']
  initContainers:
  - name: init-clone-repo
    image: alpine/git:latest
    args:
      - clone
      - --single-branch
      - --
      - https://linvirt@bitbucket.org/linvirt/dockerfiles.git
      - /tmp/repo
    volumeMounts:
    - name: git-repo
      mountPath: /tmp/repo
  volumes:
  - name: git-repo
    hostPath:
      path: /tmp/repo
